name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-on-Linux:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build
      run: |
        python3 -m pip install -r requirements.txt
        python3 -m pip install pyinstaller
        pyinstaller -F main.py

    - name: Gzip
      run: |
        cp shopid.yaml dist/
        cp config.yaml dist/
        cp LICENSE dist/
        tar -czvf linux.tar.gz dist/
    - name: Push
      run: |
        git config --global user.email 1258255974@qq.com
        git config --global user.name FionJones
        git add linux.tar.gz
        git commit -m "Update Dist"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
