# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [windows-2019, macos-10.15, ubuntu-18.04]

      steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install pyinstaller
          pyinstaller -F main.py
          
      - name: Gzip on Windows
        if: matrix.os == 'windows-2019'
        run: |
          cp shopid.yaml dist/
          cp config.yaml dist/
          cp LICENSE dist/
          tar -czvf ${{ matrix.os }}.tar.gz dist/
          
      - name: Gzip on Macos
        if: matrix.os == 'macos-10.15'
        run: |
          cp shopid.yaml dist/
          cp config.yaml dist/
          cp LICENSE dist/
          tar -czvf ${{ matrix.os }}.tar.gz dist/
      
      - name: Gzip on Ubuntu
        if: matrix.os == 'ubuntu-18.04'
        run: |
          cp shopid.yaml dist/
          cp config.yaml dist/
          cp LICENSE dist/
          tar -czvf ${{ matrix.os }}.tar.gz dist/
          
      - name: Push
        run: |
          git config --global user.email 1258255974@qq.com
          git config --global user.name FionJones
          git add linux.tar.gz
          git commit -m "Update Dist"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
